#!/bin/bash --output csv

lighthouse http://www.google.com --output csv
lighthouse http://www.youtube.com --output csv
lighthouse http://www.tmall.com --output csv
lighthouse http://www.baidu.com --output csv
lighthouse http://www.qq.com --output csv
lighthouse http://www.sohu.com --output csv
lighthouse http://www.taobao.com --output csv
lighthouse http://www.facebook.com --output csv
lighthouse http://www.amazon.com --output csv
lighthouse http://www.360.cn --output csv
lighthouse http://www.yahoo.com --output csv
lighthouse http://www.zoom.us --output csv
lighthouse http://www.jd.com --output csv
lighthouse http://www.wikipedia.org --output csv
lighthouse http://www.weibo.com --output csv
lighthouse http://www.sina.com.cn --output csv
lighthouse http://www.live.com --output csv
lighthouse http://www.reddit.com --output csv
lighthouse http://www.microsoft.com --output csv
lighthouse http://www.xinhuanet.com --output csv
lighthouse http://www.netflix.com --output csv
lighthouse http://www.office.com --output csv
lighthouse http://www.okezone.com --output csv
lighthouse http://www.vk.com --output csv
lighthouse http://www.csdn.net --output csv
lighthouse http://www.microsoftonline.com --output csv
lighthouse http://www.instagram.com --output csv
lighthouse http://www.myshopify.com --output csv
lighthouse http://www.zhanqi.tv --output csv
lighthouse http://www.yahoo.co.jp --output csv
lighthouse http://www.panda.tv --output csv
lighthouse http://www.alipay.com --output csv
lighthouse http://www.naver.com --output csv
lighthouse http://www.bongacams.com --output csv
lighthouse http://www.bing.com --output csv
lighthouse http://www.amazon.in --output csv
lighthouse http://www.google.com.hk --output csv
lighthouse http://www.twitch.tv --output csv
lighthouse http://www.ebay.com --output csv
lighthouse http://www.apple.com --output csv
lighthouse http://www.aliexpress.com --output csv
lighthouse http://www.adobe.com --output csv
lighthouse http://www.amazon.co.jp --output csv
lighthouse http://www.sharepoint.com --output csv
lighthouse http://www.google.co.in --output csv
lighthouse http://www.livejasmin.com --output csv
lighthouse http://www.yandex.ru --output csv
lighthouse http://www.twitter.com --output csv
lighthouse http://www.tianya.cn --output csv
lighthouse http://www.tribunnews.com --output csv
lighthouse http://www.huanqiu.com --output csv
lighthouse http://www.linkedin.com --output csv
lighthouse http://www.yy.com --output csv
lighthouse http://www.dropbox.com --output csv
lighthouse http://www.instructure.com --output csv
lighthouse http://www.aparat.com --output csv
lighthouse http://www.google.cn --output csv
lighthouse http://www.sogou.com --output csv
lighthouse http://www.msn.com --output csv
lighthouse http://www.wordpress.com --output csv
lighthouse http://www.chaturbate.com --output csv
lighthouse http://www.mail.ru --output csv
lighthouse http://www.17ok.com --output csv
lighthouse http://www.pornhub.com --output csv
lighthouse http://www.1688.com --output csv
lighthouse http://www.ok.ru --output csv
lighthouse http://www.google.co.jp --output csv
lighthouse http://www.whatsapp.com --output csv
lighthouse http://www.amazonaws.com --output csv
lighthouse http://www.mama.cn --output csv
lighthouse http://www.so.com --output csv
lighthouse http://www.indeed.com --output csv
lighthouse http://www.alibaba.com --output csv
lighthouse http://www.cnn.com --output csv
lighthouse http://www.google.com.br --output csv
lighthouse http://www.kumparan.com --output csv
lighthouse http://www.etsy.com --output csv
lighthouse http://www.imdb.com --output csv
lighthouse http://www.jrj.com.cn --output csv
lighthouse http://www.nytimes.com --output csv
lighthouse http://www.freepik.com --output csv
lighthouse http://www.flipkart.com --output csv
lighthouse http://www.babytree.com --output csv
lighthouse http://www.amazon.co.uk --output csv
lighthouse http://www.rakuten.co.jp --output csv
lighthouse http://www.spotify.com --output csv
lighthouse http://www.alwafd.news --output csv
lighthouse http://www.google.de --output csv
lighthouse http://www.canva.com --output csv
lighthouse http://www.okta.com --output csv
lighthouse http://www.cnblogs.com --output csv
lighthouse http://www.bbc.com --output csv
lighthouse http://www.espn.com --output csv
lighthouse http://www.walmart.com --output csv
lighthouse http://www.kompas.com --output csv
lighthouse http://www.xvideos.com --output csv
lighthouse http://www.google.fr --output csv
lighthouse http://www.hao123.com --output csv
lighthouse http://www.pixnet.net --output csv
lighthouse http://www.grid.id --output csv
lighthouse http://www.google.ru --output csv
lighthouse http://www.detik.com --output csv
lighthouse http://www.6.cn --output csv
lighthouse http://www.thestartmagazine.com --output csv
lighthouse http://www.wetransfer.com --output csv
lighthouse http://www.google.es --output csv
lighthouse http://www.stackexchange.com --output csv
lighthouse http://www.ettoday.net --output csv
lighthouse http://www.udemy.com --output csv
lighthouse http://www.savefrom.net --output csv
lighthouse http://www.zillow.com --output csv
lighthouse http://www.tumblr.com --output csv
lighthouse http://www.daum.net --output csv
lighthouse http://www.zendesk.com --output csv
lighthouse http://www.github.com --output csv
lighthouse http://www.padlet.com --output csv
lighthouse http://www.sindonews.com --output csv
lighthouse http://www.gome.com.cn --output csv
lighthouse http://www.paypal.com --output csv
lighthouse http://www.xhamster.com --output csv
lighthouse http://www.fandom.com --output csv
lighthouse http://www.stackoverflow.com --output csv
lighthouse http://www.roblox.com --output csv
lighthouse http://www.amazon.de --output csv
lighthouse http://www.soundcloud.com --output csv
lighthouse http://www.grammarly.com --output csv
lighthouse http://www.telegram.org --output csv
lighthouse http://www.quizlet.com --output csv
lighthouse http://www.tradingview.com --output csv
lighthouse http://www.shutterstock.com --output csv
lighthouse http://www.google.it --output csv
lighthouse http://www.nih.gov --output csv
lighthouse http://www.primevideo.com --output csv
lighthouse http://www.google.com.tw --output csv
lighthouse http://www.ilovepdf.com --output csv
lighthouse http://www.bilibili.com --output csv
lighthouse http://www.bbc.co.uk --output csv
lighthouse http://www.google.com.mx --output csv
lighthouse http://www.salesforce.com --output csv
lighthouse http://www.indiatimes.com --output csv
lighthouse http://www.zhihu.com --output csv
lighthouse http://www.vimeo.com --output csv
lighthouse http://www.chase.com --output csv
lighthouse http://www.theguardian.com --output csv
lighthouse http://www.speedtest.net --output csv
lighthouse http://www.onlinesbi.com --output csv
lighthouse http://www.pikiran-rakyat.com --output csv
lighthouse http://www.eastday.com --output csv
lighthouse http://www.bet9ja.com --output csv
lighthouse http://www.wix.com --output csv
lighthouse http://www.researchgate.net --output csv
lighthouse http://www.booking.com --output csv
lighthouse http://www.pixabay.com --output csv
lighthouse http://www.tiktok.com --output csv
lighthouse http://www.google.com.sg --output csv
lighthouse http://www.pinterest.com --output csv
lighthouse http://www.amazon.ca --output csv
lighthouse http://www.youm7.com --output csv
lighthouse http://www.tokopedia.com --output csv
lighthouse http://www.digikala.com --output csv
lighthouse http://www.slideshare.net --output csv
lighthouse http://www.craigslist.org --output csv
lighthouse http://www.tistory.com --output csv
lighthouse http://www.washingtonpost.com --output csv
lighthouse http://www.google.com.tr --output csv
lighthouse http://www.duckduckgo.com --output csv
lighthouse http://www.163.com --output csv
lighthouse http://www.hotstar.com --output csv
lighthouse http://www.google.co.uk --output csv
lighthouse http://www.avito.ru --output csv
lighthouse http://www.forbes.com --output csv
lighthouse http://www.setn.com --output csv
lighthouse http://www.healthline.com --output csv
lighthouse http://www.iqiyi.com --output csv
lighthouse http://www.wellsfargo.com --output csv
lighthouse http://www.cnet.com --output csv
lighthouse http://www.w3schools.com --output csv
lighthouse http://www.rednet.cn --output csv
lighthouse http://www.foxnews.com --output csv
lighthouse http://www.ups.com --output csv
lighthouse http://www.godaddy.com --output csv
lighthouse http://www.mediafire.com --output csv
lighthouse http://www.fedex.com --output csv
lighthouse http://www.webex.com --output csv
lighthouse http://www.force.com --output csv
lighthouse http://www.bestbuy.com --output csv
lighthouse http://www.liputan6.com --output csv
lighthouse http://www.investing.com --output csv
lighthouse http://www.metropoles.com --output csv
lighthouse http://www.ca.gov --output csv
lighthouse http://www.ikea.com --output csv
lighthouse http://www.worldometers.info --output csv
lighthouse http://www.usps.com --output csv
lighthouse http://www.line.me --output csv
lighthouse http://www.google.ca --output csv
lighthouse http://www.momoshop.com.tw --output csv
lighthouse http://www.businessinsider.com --output csv
lighthouse http://www.google.com.sa --output csv
lighthouse http://www.smallpdf.com --output csv
lighthouse http://www.skype.com --output csv
lighthouse http://www.bukalapak.com --output csv
lighthouse http://www.wikihow.com --output csv
lighthouse http://www.varzesh3.com --output csv
lighthouse http://www.hdfcbank.com --output csv
lighthouse http://www.box.com --output csv
lighthouse http://www.suara.com --output csv
lighthouse http://www.ebay.de --output csv
lighthouse http://www.51.la --output csv
lighthouse http://www.aliexpress.ru --output csv
lighthouse http://www.google.com.ar --output csv
lighthouse http://www.onmarshtompor.com --output csv
lighthouse http://www.breitbart.com --output csv
lighthouse http://www.deepl.com --output csv
lighthouse http://www.blackboard.com --output csv
lighthouse http://www.google.com.eg --output csv
lighthouse http://www.cnbc.com --output csv
lighthouse http://www.360.com --output csv
lighthouse http://www.fivethirtyeight.com --output csv
lighthouse http://www.chegg.com --output csv
lighthouse http://www.t.me --output csv
lighthouse http://www.homedepot.com --output csv
lighthouse http://www.amazon.cn --output csv
lighthouse http://www.taboola.com --output csv
lighthouse http://www.haosou.com --output csv
lighthouse http://www.uol.com.br --output csv
lighthouse http://www.ladbible.com --output csv
lighthouse http://www.behance.net --output csv
lighthouse http://www.51sole.com --output csv
lighthouse http://www.target.com --output csv
lighthouse http://www.borna.news --output csv
lighthouse http://www.gosuslugi.ru --output csv
lighthouse http://www.hulu.com --output csv
lighthouse http://www.zerodha.com --output csv
lighthouse http://www.kakao.com --output csv
lighthouse http://www.namnak.com --output csv
lighthouse http://www.aliyun.com --output csv
lighthouse http://www.ebay.co.uk --output csv
lighthouse http://www.reverso.net --output csv
lighthouse http://www.amazon.fr --output csv
lighthouse http://www.heavy.com --output csv
lighthouse http://www.japanpost.jp --output csv
lighthouse http://www.google.co.th --output csv
lighthouse http://www.bbcollab.com --output csv
lighthouse http://www.sciencedirect.com --output csv
lighthouse http://www.medium.com --output csv
lighthouse http://www.merdeka.com --output csv
lighthouse http://www.chouftv.ma --output csv
lighthouse http://www.icicibank.com --output csv
lighthouse http://www.t.co --output csv
lighthouse http://www.samsung.com --output csv
lighthouse http://www.mercari.com --output csv
lighthouse http://www.madrasati.sa --output csv
lighthouse http://www.capitalone.com --output csv
lighthouse http://www.hp.com --output csv
lighthouse http://www.patria.org.ve --output csv
lighthouse http://www.coursera.org --output csv
lighthouse http://www.ltn.com.tw --output csv
lighthouse http://www.bet365.com --output csv
lighthouse http://www.videocampaign.co --output csv
lighthouse http://www.adblockplus.org --output csv
lighthouse http://www.payoneer.com --output csv
lighthouse http://www.airbnb.com --output csv
lighthouse http://www.cloudfront.net --output csv
lighthouse http://www.discord.com --output csv
lighthouse http://www.dailymail.co.uk --output csv
lighthouse http://www.redd.it --output csv
lighthouse http://www.mercadolibre.com.ar --output csv
lighthouse http://www.hootsuite.com --output csv
lighthouse http://www.glassdoor.com --output csv
lighthouse http://www.lazada.sg --output csv
lighthouse http://www.patch.com --output csv
lighthouse http://www.soso.com --output csv
lighthouse http://www.sahibinden.com --output csv
lighthouse http://www.scribd.com --output csv
lighthouse http://www.manoramaonline.com --output csv
lighthouse http://www.investopedia.com --output csv
lighthouse http://www.weebly.com --output csv
lighthouse http://www.cricbuzz.com --output csv
lighthouse http://www.thesaurus.com --output csv
lighthouse http://www.y2mate.com --output csv
lighthouse http://www.google.co.id --output csv
lighthouse http://www.geeksforgeeks.org --output csv
lighthouse http://www.amazon.it --output csv
lighthouse http://www.abs-cbn.com --output csv
lighthouse http://www.mercadolivre.com.br --output csv
lighthouse http://www.goodreads.com --output csv
lighthouse http://www.mozilla.org --output csv
lighthouse http://www.squarespace.com --output csv
lighthouse http://www.telewebion.com --output csv
lighthouse http://www.steampowered.com --output csv
lighthouse http://www.proiezionidiborsa.it --output csv
lighthouse http://www.shaparak.ir --output csv
lighthouse http://www.mercadolibre.com.mx --output csv
lighthouse http://www.chess.com --output csv
lighthouse http://www.google.pl --output csv
lighthouse http://www.trello.com --output csv
lighthouse http://www.ask.com --output csv
lighthouse http://www.googlevideo.com --output csv
lighthouse http://www.haofang.net --output csv
lighthouse http://www.iqbroker.com --output csv
lighthouse http://www.namu.wiki --output csv
lighthouse http://www.blogger.com --output csv
lighthouse http://www.istockphoto.com --output csv
lighthouse http://www.ndtv.com --output csv
lighthouse http://www.fc2.com --output csv
lighthouse http://www.amazon.es --output csv
lighthouse http://www.wikimedia.org --output csv
lighthouse http://www.weather.com --output csv
lighthouse http://www.pinimg.com --output csv
lighthouse http://www.chinaz.com --output csv
lighthouse http://www.indiamart.com --output csv
lighthouse http://www.nicovideo.jp --output csv
lighthouse http://www.dailymotion.com --output csv
lighthouse http://www.idntimes.com --output csv
lighthouse http://www.fidelity.com --output csv
lighthouse http://www.wayfair.com --output csv
lighthouse http://www.trustpilot.com --output csv
lighthouse http://www.hurriyet.com.tr --output csv
lighthouse http://www.schoology.com --output csv
lighthouse http://www.jianshu.com --output csv
lighthouse http://www.rambler.ru --output csv
lighthouse http://www.sonhoo.com --output csv
lighthouse http://www.wsj.com --output csv
lighthouse http://www.wixsite.com --output csv
lighthouse http://www.figma.com --output csv
lighthouse http://www.feedly.com --output csv
lighthouse http://www.quora.com --output csv
lighthouse http://www.wildberries.ru --output csv
lighthouse http://www.ameblo.jp --output csv
lighthouse http://www.softonic.com --output csv
lighthouse http://www.ebc.net.tw --output csv
lighthouse http://www.docusign.net --output csv
lighthouse http://www.ballotpedia.org --output csv
lighthouse http://www.nike.com --output csv
lighthouse http://www.tutorialspoint.com --output csv
lighthouse http://www.fiverr.com --output csv
lighthouse http://www.realtor.com --output csv
lighthouse http://www.google.com.au --output csv
lighthouse http://www.moneycontrol.com --output csv
lighthouse http://www.oracle.com --output csv
lighthouse http://www.allegro.pl --output csv
lighthouse http://www.academia.edu --output csv
lighthouse http://www.gmx.net --output csv
lighthouse http://www.marketwatch.com --output csv
lighthouse http://www.ouedkniss.com --output csv
lighthouse http://www.cambridge.org --output csv
lighthouse http://www.globo.com --output csv
lighthouse http://www.twimg.com --output csv
lighthouse http://www.mheducation.com --output csv
lighthouse http://www.google.co.kr --output csv
lighthouse http://www.shopee.tw --output csv
lighthouse http://www.xfinity.com --output csv
lighthouse http://www.naukri.com --output csv
lighthouse http://www.khanacademy.org --output csv
lighthouse http://www.coupang.com --output csv
lighthouse http://www.inquirer.net --output csv
lighthouse http://www.codepen.io --output csv
lighthouse http://www.state.gov --output csv
lighthouse http://www.rt.com --output csv
lighthouse http://www.dell.com --output csv
lighthouse http://www.beytoote.com --output csv
lighthouse http://www.adp.com --output csv
lighthouse http://www.messenger.com --output csv
lighthouse http://www.web.de --output csv
lighthouse http://www.tencent.com --output csv
lighthouse http://www.ensonhaber.com --output csv
lighthouse http://www.ria.ru --output csv
lighthouse http://www.surveymonkey.com --output csv
lighthouse http://www.google.gr --output csv
lighthouse http://www.thepiratebay.org --output csv
lighthouse http://www.patreon.com --output csv
lighthouse http://www.in.gr --output csv
lighthouse http://www.liansuo.com --output csv
lighthouse http://www.aol.com --output csv
lighthouse http://www.shimo.im --output csv
lighthouse http://www.ih5.cn --output csv
lighthouse http://www.op.gg --output csv
lighthouse http://www.zoho.com --output csv
lighthouse http://www.xnxx.com --output csv
lighthouse http://www.infobae.com --output csv
lighthouse http://www.fast.com --output csv
lighthouse http://www.canada.ca --output csv
lighthouse http://www.gamepedia.com --output csv
lighthouse http://www.sberbank.ru --output csv
lighthouse http://www.costco.com --output csv
lighthouse http://www.ebay-kleinanzeigen.de --output csv
lighthouse http://www.iyiou.com --output csv
lighthouse http://www.usatoday.com --output csv
lighthouse http://www.genius.com --output csv
lighthouse http://www.yts.mx --output csv
lighthouse http://www.azure.com --output csv
lighthouse http://www.jpnn.com --output csv
lighthouse http://www.google.com.vn --output csv
lighthouse http://www.google.az --output csv
lighthouse http://www.divar.ir --output csv
lighthouse http://www.cnnic.cn --output csv
lighthouse http://www.zol.com.cn --output csv
lighthouse http://www.asos.com --output csv
lighthouse http://www.slack.com --output csv
lighthouse http://www.tahiamasr.com --output csv
lighthouse http://www.cnzz.com --output csv
lighthouse http://www.efu.com.cn --output csv
lighthouse http://www.gusuwang.com --output csv
lighthouse http://www.nikkei.com --output csv
lighthouse http://www.gotomeeting.com --output csv
lighthouse http://www.ebay.com.au --output csv
lighthouse http://www.hm.com --output csv
lighthouse http://www.gotowebinar.com --output csv
lighthouse http://www.pearson.com --output csv
lighthouse http://www.shopee.co.id --output csv
lighthouse http://www.gstatic.com --output csv
lighthouse http://www.list-manage.com --output csv
lighthouse http://www.disneyplus.com --output csv
lighthouse http://www.oschina.net --output csv
lighthouse http://www.wp.pl --output csv
lighthouse http://www.runoob.com --output csv
lighthouse http://www.mit.edu --output csv
lighthouse http://www.constantcontact.com --output csv
lighthouse http://www.redbubble.com --output csv
lighthouse http://www.get-express-vpn.online --output csv
lighthouse http://www.reuters.com --output csv
lighthouse http://www.att.com --output csv
lighthouse http://www.linktr.ee --output csv
lighthouse http://www.archive.org --output csv
lighthouse http://www.marca.com --output csv
lighthouse http://www.files.wordpress.com --output csv
lighthouse http://www.saednews.com --output csv
lighthouse http://www.webmd.com --output csv
lighthouse http://www.citi.com --output csv
lighthouse http://www.mseav.com --output csv
lighthouse http://www.verizon.com --output csv
lighthouse http://www.banvenez.com --output csv
lighthouse http://www.ekaie.com --output csv
lighthouse http://www.huaban.com --output csv
lighthouse http://www.dcard.tw --output csv
lighthouse http://www.wiley.com --output csv
lighthouse http://www.ibicn.com --output csv
lighthouse http://www.outbrain.com --output csv
lighthouse http://www.hindnow.com --output csv
lighthouse http://www.104.com.tw --output csv
lighthouse http://www.tandfonline.com --output csv
lighthouse http://www.quizizz.com --output csv
lighthouse http://www.gismeteo.ru --output csv
lighthouse http://www.alodokter.com --output csv
lighthouse http://www.td.com --output csv
lighthouse http://www.arcgis.com --output csv
lighthouse http://www.oxu.az --output csv
lighthouse http://www.ecv360.com --output csv
lighthouse http://www.donya-e-eqtesad.com --output csv
lighthouse http://www.pngtree.com --output csv
lighthouse http://www.mfisp.com --output csv
lighthouse http://www.intuit.com --output csv
lighthouse http://www.irs.gov --output csv
lighthouse http://www.namasha.com --output csv
lighthouse http://www.81.cn --output csv
lighthouse http://www.agacelebir.com --output csv
lighthouse http://www.atharori.net --output csv
lighthouse http://www.dhl.com --output csv
lighthouse http://www.google.com.ua --output csv
lighthouse http://www.cpic.com.cn --output csv
lighthouse http://www.srvtrck.com --output csv
lighthouse http://www.bankofamerica.com --output csv
lighthouse http://www.dbs.com.sg --output csv
lighthouse http://www.vnexpress.net --output csv
lighthouse http://www.goo.ne.jp --output csv
lighthouse http://www.ameritrade.com --output csv
lighthouse http://www.zara.com --output csv
lighthouse http://www.springer.com --output csv
lighthouse http://www.yc58.com --output csv
lighthouse http://www.issuu.com --output csv
lighthouse http://www.slickdeals.net --output csv
lighthouse http://www.onet.pl --output csv
lighthouse http://www.58.com --output csv
lighthouse http://www.kapanlagi.com --output csv
lighthouse http://www.go.com --output csv
lighthouse http://www.qoo10.sg --output csv
lighthouse http://www.tripadvisor.com --output csv
lighthouse http://www.spankbang.com --output csv
lighthouse http://www.elintransigente.com --output csv
lighthouse http://www.npr.org --output csv
lighthouse http://www.caigou2003.com --output csv
lighthouse http://www.coursehero.com --output csv
lighthouse http://www.desmos.com --output csv
lighthouse http://www.wordreference.com --output csv
lighthouse http://www.wish.com --output csv
lighthouse http://www.1337x.to --output csv
lighthouse http://www.myworkdayjobs.com --output csv
lighthouse http://www.milliyet.com.tr --output csv
lighthouse http://www.justdial.com --output csv
lighthouse http://www.caf.fr --output csv
lighthouse http://www.turkiye.gov.tr --output csv
lighthouse http://www.mos.ru --output csv
lighthouse http://www.orange.fr --output csv
lighthouse http://www.kakaku.com --output csv
lighthouse http://www.giphy.com --output csv
lighthouse http://www.europa.eu --output csv
lighthouse http://www.getadblock.com --output csv
lighthouse http://www.kundelik.kz --output csv
lighthouse http://www.bp.blogspot.com --output csv
lighthouse http://www.fun48.com --output csv
